### ISSUE TITLE
The solution event with Action "AddProjectItem" triggers in unexpected context

### ISSUE THREAD

**Issue by markuszm** [stg-tud/kave#10]
* When opening a File e.g. a textfile that is not included in the opened project a solution event with Action "AddProjectItem" triggers
* When opening a external class that is not in the opened project e.g. a líbary Class inside code it also triggers a solution event with Action "AddProjectItem"

**Comment by salsolatragus** [comment]
It seems that AddProjectItem has a different semantics from what we assumed. We should consider renaming the events to make things less confusing. In addition, should we try to fire real "item added" events?

**Comment by salsolatragus** [comment]
We decided to simply ignore these events entirely.
