### ISSUE TITLE
Wait for N events before showing the Export Wizard

### ISSUE THREAD

**Issue by proksch** [stg-tud/kave#14]
Some users complained that the export wizard pops up, even though they did not use Visual Studio rarely or not at all. I would suggest that we implement a check that the export wizard does not pop-up if less than N events have been recorded.

The exact N needs to be evaluated, I would suggest starting with 100? 500? 1000?

**Comment by salsolatragus** [comment]
I've implemented a check for the current event logs' accumulated file size. Reminders now only appear if the size exceeds 500 KB.
