### ISSUE TITLE
IDEEvent data is incompletely saved 

### ISSUE THREAD

**Issue by markuszm** [stg-tud/kave#16]
In the Json File some attributes of events are empty.
The most recent version was used (0.764)
Examples:
#### Window Event:
The Fields "Window" and "ActiveWindow" are empty in the JSON File / Json View
example event in Design View:
![image](https://cloud.githubusercontent.com/assets/9436263/7283431/ca7ceee6-e936-11e4-9cde-713b861b555c.png)
Json View:
>
{
    "$type": "KaVE.Commons.Model.Events.VisualStudio.WindowEvent, KaVE.Commons",
    "Window": "",
    "Action": 3,
    "IDESessionUUID": "b295a5cb-706d-4e43-b86c-2c2b6be04914",
    "KaVEVersion": "0.764",
    "TriggeredAt": "2015-04-22T21:26:09.2550392+02:00",
    "TriggeredBy": 0,
    "Duration": "00:00:00",
    "ActiveWindow": ""
} 
>

#### Document Event:
Fields "Document" and "ActiveWindow" are empty 
example event in Design View:
![image](https://cloud.githubusercontent.com/assets/9436263/7283496/4a1e7232-e937-11e4-9607-5bcb59b50f81.png)
Json View:
>{
    "$type": "KaVE.Commons.Model.Events.VisualStudio.DocumentEvent, KaVE.Commons",
    "Document": "",
    "Action": 0,
    "IDESessionUUID": "b295a5cb-706d-4e43-b86c-2c2b6be04914",
    "KaVEVersion": "0.764",
    "TriggeredAt": "2015-04-22T21:33:45.8761564+02:00",
    "TriggeredBy": 0,
    "Duration": "00:00:00.0010001",
   "ActiveWindow": ""
}
>

#### Solution Event:
Fields "Target", "ActiveWindow" and "ActiveDocument" are empty.
example event in Design View:
![image](https://cloud.githubusercontent.com/assets/9436263/7283582/df2842cc-e937-11e4-81c6-316dd02c1d0d.png)
Json View:
> {
    "$type": "KaVE.Commons.Model.Events.VisualStudio.SolutionEvent, KaVE.Commons",
    "Action": 2,
    "Target": "",
    "IDESessionUUID": "b295a5cb-706d-4e43-b86c-2c2b6be04914",
    "KaVEVersion": "0.764",
    "TriggeredAt": "2015-04-22T21:34:55.0321119+02:00",
    "TriggeredBy": 0,
    "Duration": "00:00:00.0010001",
    "ActiveWindow": "",
    "ActiveDocument": ""
} 
>

**Comment by salsolatragus** [comment]
This problem was probably introduced when we refactored out project structure. Somehow the lookup of the type converter for names failed and fell back to the default converter. I fixed it in 6d55b2dbc1 by explicitly using our converter instead of relying on the right one being looked up by the language mechanism.
