### ISSUE TITLE
IDE Shutdown is not tracked correctly

### ISSUE THREAD

**Issue by markuszm** [stg-tud/kave#18]
When closing the IDE with the Exit Button or with the shortcut "ALT+F4", the Feedback Manager does not trigger a IDEEventState Event with "IDELifecyclePhase": "Shutdown".

At the moment one way to trigger this event is for example by updating the Feedback Manager plugin. The forced restart after the update triggers a IDEEventState Event with "IDELifecyclePhase": "Shutdown".

KaVE Version: 0.774

**Comment by salsolatragus** [comment]
Yes, I observed this too. Thanks for the report. Unfortunately, I don't see a way to fix this, since in the cases where we don't get the event, it seems we're just not notified of the shutdown at all... we're working on a heuristic to reconstruct missing shutdown events from the event stream.
