### ISSUE TITLE
Uploading large amount of feedback results in ZIP exception

### ISSUE THREAD

**Issue by proksch** [stg-tud/kave#19]
I just received a bug report from a user:

> ich bekomme immer eine Exception beim Export der Daten (egal ob direkt Export oder per ZIP-File): ![upload-zip-error](https://cloud.githubusercontent.com/assets/5196491/7474662/1bd2190e-f343-11e4-82d1-0d7aba66f60b.png)

Obviously, our logic to upload files does not check if we generate valid ZIP files and tries to put too many files into the ZIP. There might be three alternatives:

* Giving the mentioned property a shot (UseZip64WhenSaving), but it seems that this property is only available in .net 4.5+
* Exchanging the compression library (to something that supports ZIP64 in .net 4.0)
* Exchanging the compression format

Unfortunately, we also need to adapt the server part, because cleans the upload and creates new ZIP files as well, we need to implement a similar fix there.

**Comment by salsolatragus** [comment]
I configured the export to use ZIP64, if required. This seems to work. Unfortunately, I'm not sure wether the server can read these files. According to Oracle's specification Java's ZipFile "may optionally support ... ZIP64" (http://docs.oracle.com/javase/7/docs/api/java/util/zip/package-summary.html), so it depends on the server's Java. We have to check that before we can declare this closed...

**Comment by salsolatragus** [comment]
Should work with any JDK/JRE 7 and above. Just successfully uploaded 66k events ;)
