### ISSUE TITLE
Missing Icon for EventManager?

### ISSUE THREAD

**Issue by salsolatragus** [stg-tud/kave#22]
When reinstalling ReSharper I just got the following error. Might be nothing, might be something we should look into. Not sure...

> Execute Build Step Runnable JetBrains.Platform.VisualStudio.Core!JetBrains.VsIntegration.UI.WindowManagement.Install.VsPackageEmitsToolWindowIcons::CollectToolWindowIcons#3 has failed. The build step method JetBrains.VsIntegration.UI.WindowManagement.Install.VsPackageEmitsToolWindowIcons::CollectToolWindowIcons has thrown an exception. Exception has been thrown by the target of an invocation. Unresolved icon SearchOptionsPage referenced by the Tool Window SessionManagerFeedbackWindow in assembly KaVE.VS.FeedbackGenerator. Are you missing an assembly reference to JetBrains.ReSharper.Features.Navigation, Version=102.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325?

**Comment by proksch** [comment]
Installation errors were fixed in one of the last commits.
