### ISSUE TITLE
LoggerException when opening a project

### ISSUE THREAD

**Issue by M8is** [stg-tud/kave#25]
I sometimes get a [LoggerException with the message “The execution context must be guarded from reentrancy in order to execute this action.”](https://github.com/stg-tud/kave/files/6574/LoggerException.txt) when opening a project. I didn't find a way to reproduce it, but it seems to happen pretty regularly.

**Comment by M8is** [comment]
I have also experienced a deadlock when using CodeCleanup on a file I just edited. 
This seems reproduceable: Edit a file, wait for about a second, trigger CodeCleanup. The CodeCleanup Window opens, but never finishes. 
This might be related, since I experienced these issues only since EditEvents are enabled again.

**Comment by salsolatragus** [comment]
I guarded the context generation for Reentrancy. This seems to be required for it to execute in the context of some R# actions. E.g. if edits are cause by CodeCleanup. I'm not sure if we still need the ReadLock, but I left it there, just in case...

@M8is: You told me that you get no deadlocks anymore, does this include the scenario you described above?

**Comment by M8is** [comment]
Yes, it hasn't happened to me for a while and I can't reproduce it anymore.
