### ISSUE TITLE
FeedbackManager pane has no content on first access

### ISSUE THREAD

**Issue by proksch** [stg-tud/kave#3]
After installing the FeedbackGenerator, the FeedbackManager pane is empty on first access.

**Comment by proksch** [comment]
I witnessed this issue on several DATEV machines, however, I cannot reproduce it locally. It may be fixed by the reworked exception handling strategy.

**Comment by proksch** [comment]
I just reproduced the issue locally by installing a manually built package in VS2013 with R#-8.2.3.

**Comment by proksch** [comment]
Even though this problem does not occur when starting the plugin in a debugging session, there are other potentially related issues... for me, the list of events is always empty, when a session is selected (after upload only?). It is necessary to re-open the Feedback Manager to get rid of this.

**Comment by salsolatragus** [comment]
This sounds very much like a race condition in the initialisation of the window. In VS windows are not disposed and recreated, but only hidden and (partly) reinitialised, when closed and reopened. Maybe we should look at what parts are reinitialised to identify potential causes for this problem.

**Comment by salsolatragus** [comment]
Was actually a problem with our dependency for the loading animation that could not be loaded in VS13. We replaced the animation and removed the dependency. Solved the issue for me.
