### ISSUE TITLE
Solution Events "AddProjectItem" & "RemoveProjectItem" don't trigger when Adding new Items in Solution Explorer

### ISSUE THREAD

**Issue by markuszm** [stg-tud/kave#7]
Adding new items in the Solution Explorer via Right Click -> Add -> New Item... or via the context menu Project -> Add New Item... should trigger a SolutionEvent with Action: "AddProjectItem"

Adding new classes via the context menu Project -> Add Class... should also trigger a SolutionEvent with Action: "AddProjectItem"

Removing Items inside the Solution Explorer via Right Click on the file -> Delete or Shortcut Del should trigger a SolutionEvent with Action: "RemoveProjectItem"

**Comment by salsolatragus** [comment]
We decided to simply ignore these events entirely.
