### ISSUE TITLE
Commits don't trigger a Command Event when clicking on Commit Button in Git Team Explorer 

### ISSUE THREAD

**Issue by markuszm** [stg-tud/kave#8]
Commits only trigger a Command Event when using the dropdown menu in the TeamExplorer next to the Commit Button (Highlighted on the included picture). They should also trigger on clicking the Commit Button.
![untitled](https://cloud.githubusercontent.com/assets/9436263/5920772/592b1bee-a63f-11e4-8951-0149e1eec10d.png)

**Comment by salsolatragus** [comment]
This has been fixed in the latest release.
