### ISSUE TITLE
Command Events don't trigger consistently when setting the language of Visual Studio to german 

### ISSUE THREAD

**Issue by markuszm** [stg-tud/kave#9]
Example:
Clicking on Save All button

With english language setting these two events trigger:
* {
    "$type": "KaVE.Model.Events.CommandEvent, KaVE.Model",
    "CommandId": "{5EFC7975-14BC-11CF-9B2B-00AA00573819}:224:File.SaveAll",
    "IDESessionUUID": "03deeca8-2f4d-415a-920a-f3b19e53ea6a",
    "KaVEVersion": "0.728",
    "TriggeredAt": "2015-02-11T19:24:16.2518357+01:00",
    "TriggeredBy": 0,
    "Duration": "00:00:00.0200011",
    "ActiveWindow": "VisualStudio.WindowName:vsWindowTypeToolWindow Feedback Manager"
 }
* {
    "$type": "KaVE.Model.Events.CommandEvent, KaVE.Model",
    "CommandId": "Save All",
    "IDESessionUUID": "03deeca8-2f4d-415a-920a-f3b19e53ea6a",
    "KaVEVersion": "0.728",
    "TriggeredAt": "2015-02-11T19:24:23.7482645+01:00",
    "TriggeredBy": 1,
    "ActiveWindow": "VisualStudio.WindowName:vsWindowTypeToolWindow Feedback Manager"
}

With german language setting only the event triggered by the click occurs:
* {
    "$type": "KaVE.Model.Events.CommandEvent, KaVE.Model",
    "CommandId": "Alles speichern",
    "IDESessionUUID": "03deeca8-2f4d-415a-920a-f3b19e53ea6a",
    "KaVEVersion": "0.728",
    "TriggeredAt": "2015-02-11T19:26:50.8206765+01:00",
    "TriggeredBy": 1,
    "ActiveWindow": "VisualStudio.WindowName:vsWindowTypeToolWindow Feedback Manager"
 }

This also applies to Commands like Add new element or File Open.

Strangely not all Commands have this behavior and Commands like opening the Options Page of Visual Studio or File.NewProject trigger the same events as in the english Visual Studio version.

**Comment by salsolatragus** [comment]
For those command events that are triggered with language set to German: Do they have the same CommandId as with English or is the id translated?

**Comment by markuszm** [comment]
The command event that is triggered by a click is has a german command id.
The other one is in english 
e.g. command ids for command events triggered by opening the options page of Visual Studio:
German Language setting: 
1. Event: "CommandId": "Optionen..." triggered by click
2. Event: "CommandId": "{5EFC7975-14BC-11CF-9B2B-00AA00573819}:264:Tools.Options"  

English Language setting:
1. Event: "CommandId": "Options..." triggered by click
2. Event: "CommandId": "{5EFC7975-14BC-11CF-9B2B-00AA00573819}:264:Tools.Options"

**Comment by salsolatragus** [comment]
Fixed in current release. Only works for German (and English), though.
